export const INSTITUTION_OPTIONS = [
  // FAST (first as requested)
  "National University of Computer and Emerging Sciences (FAST), Karachi",
  "National University of Computer and Emerging Sciences (FAST), Islamabad",
  "National University of Computer and Emerging Sciences (FAST), Lahore",
  "National University of Computer and Emerging Sciences (FAST), Peshawar",
  "National University of Computer and Emerging Sciences (FAST), Chiniot",

  // Federal/Public Sector Universities
  "COMSATS Institute of Information Technology, Abbottabad",
  "COMSATS Institute of Information Technology, Attock",
  "COMSATS Institute of Information Technology, Lahore",
  "COMSATS Institute of Information Technology, Wah",
  "COMSATS Institute of Information Technology, Vehari",
  "COMSATS Institute of Information Technology, Sahiwal",
  "Federal Urdu University of Arts, Sciences & Technology, Islamabad",
  "Federal Urdu University of Arts, Sciences & Technology, Karachi",
  "National University of Modern Languages (NUML), Islamabad",
  "National University of Modern Languages (NUML), Lahore",
  "National University of Modern Languages (NUML), Faisalabad",
  "National University of Modern Languages (NUML), Peshawar",
  "National University of Modern Languages (NUML), Multan",
  "National University of Modern Languages (NUML), Karachi",
  "National University of Modern Languages (NUML), Hyderabad",
  "National University of Modern Languages (NUML), Quetta",
  "National University of Modern Languages (NUML), Rawalpindi",
  "National University of Modern Languages (NUML), Mirpur AJ&K",
  "National College of Arts (NCA), Lahore",
  "National College of Arts, Rawalpindi",
  "Bahria University, Islamabad",
  "Bahria University, Karachi",
  "Bahria University, Lahore",
  "Air University, Islamabad",
  "Air University, Multan",
  "Air University, Kamra",
  "Air University, Kharian",
  "Air University, Lahore (NIIT)",
  "Air University, Karachi",
  "Virtual University of Pakistan, Islamabad",
  "Virtual University of Pakistan, Rawalpindi",
  "Virtual University of Pakistan, DG Khan",
  "Virtual University of Pakistan, Faisalabad",
  "Virtual University of Pakistan, Gujranwala",
  "Virtual University of Pakistan, Multan",
  "Virtual University of Pakistan, Sahiwal",
  "Virtual University of Pakistan, Badin",
  "Virtual University of Pakistan, Ghotki",
  "Virtual University of Pakistan, Karachi",
  "Virtual University of Pakistan, Pashin",
  "Virtual University of Pakistan, Peshawar",
  "Virtual University of Pakistan, Muzaffargarh",
  "Mehran University of Engineering & Technology, Jamshoro",
  "Mehran University of Engineering & Technology, Khairpur",
  "Shah Abdul Latif University, Khairpur",
  "Shah Abdul Latif University, Ghotki",
  "Shah Abdul Latif University, Shahdadkot",
  "University of Sindh, Jamshoro",
  "University of Sindh, Mirpur Khas",
  "University of Sindh, Badin",
  "University of Sindh, Dadu",
  "Quaid‑i‑Awan University of Engineering & Technology, Nawabshah",
  "Quaid‑i‑Awan University of Engineering & Technology, Larkana",
  "Shaheed Benazir Bhutto University, Shaheed Benazirabad",
  "Shaheed Benazir Bhutto University, Naushahro Feroze",
  "Sindh Agriculture University, Tandojam",
  "Sindh Agriculture University, Umerkot",
  "NED University of Engineering & Technology, Karachi",
  "NED University of Engineering & Technology, Mithi‑Tharparkar",
  "Dow University of Health Sciences, Karachi",
  "Dow University of Health Sciences, Ojha Campus",
  "University of Engineering & Technology (UET), Lahore",
  "University of Engineering & Technology (UET), Kalashah Kako",
  "University of Engineering & Technology (UET), Faisalabad",
  "University of Engineering & Technology (UET), Rachna College Gujranwala",
  "University of Engineering & Technology (UET), Narowal",
  "University of Punjab, Lahore",
  "University of Punjab, Gujranwala",
  "University of Punjab, Jhelum",
  "Lahore College for Women University (LCWU), Lahore",
  "University of Education, Lahore",
  "University of Education, Okara",
  "University of Education, DG Khan",
  "University of Education, Faisalabad",
  "University of Education, Joharabad",
  "University of Education, Multan",
  "University of Education, Vehari",
  "University of Veterinary & Animal Sciences (UVAS), Lahore",
  "University of Veterinary & Animal Sciences (UVAS), Patoki",
  "University of Veterinary & Animal Sciences (UVAS), Jhang",
  "University of Veterinary & Animal Sciences (UVAS), Narowal",
  "Islamia University, Bahawalpur",
  "Islamia University, Rahim Yar Khan",
  "Islamia University, Bahawalnagar",
  "Bahauddin Zakariya University (BZU), Multan",
  "Bahauddin Zakariya University (BZU), Vehari",
  "Bahauddin Zakariya University (BZU), Lodhran",
  "Karakorum International University, Gilgit‑Baltistan",
  "Karakorum International University, Hunza",
  "Karakorum International University, Diamer (Chilas)",
  "Karakorum International University, Ghizer",
  "University of Engineering & Technology (UET), Peshawar",
  "University of Engineering & Technology (UET), Abbottabad",
  "University of Engineering & Technology (UET), Swat",
  "University of Engineering & Technology (UET), Mardan",
  "University of Engineering & Technology (UET), Bannu",
  "University of Engineering & Technology (UET), Jalozai",
  "University of Engineering & Technology (UET), Kohat",
  "Shaheed Benazir Bhutto University, Sheringal",
  "Shaheed Benazir Bhutto University, Wari",
  "University of Swat, Swat",
  "University of Malakand, Malakand",
  "Kohat University of Science & Technology (KUST), Kohat",
  "Kohat University of Science & Technology (KUST), Hangu",
  "Gomal University, Dera Ismail Khan",
  "Gomal University, Tank",
  "Hazara University, Mansehra",
  "Hazara University, Battagram",
  "University of Turbat, Turbat",
  "University of Turbat, Gwadar",
  "University of Turbat, Pangjur",
  "Sardar Bahadur Khan Women University, Quetta",
  "Sardar Bahadur Khan Women University, Pishin",
  "Sardar Bahadur Khan Women University, Noshki",
  "Sardar Bahadur Khan Women University, Khuzdar",
  "Balochistan University of Information Technology, Engineering & Management Sciences (BUITEMS), Quetta",
  "Balochistan University of Information Technology, Engineering & Management Sciences (BUITEMS), Zhob College",
  "Balochistan University of Engineering & Technology (BUET), Khuzdar",
  "Balochistan University of Engineering & Technology (BUET), Uthal",
  "Lasbela University of Agriculture, Water & Marine Sciences (LUAWMS), Uthal",
  "Lasbela University of Agriculture, Water & Marine Sciences (LUAWMS), Wadh",
  "Lasbela University of Agriculture, Water & Marine Sciences (LUAWMS), Dera Murad Jamali",
  "University of Balochistan, Quetta",
  "University of Balochistan, Mastung",
  "University of Balochistan, Kharan",
  "University of Poonch, Rawalakot",
  "University of Poonch, Kahuta Haveli",
  "University of Azad Jammu & Kashmir, Muzaffarabad",
  "University of Azad Jammu & Kashmir, Athmuqam",

  // Private Sector Universities/DAIs
  "University of Lahore, Lahore",
  "University of Lahore, Sargodha",
  "Preston University, Kohat",
  "Preston University, Islamabad",
  "SZABIST, Karachi",
  "SZABIST, Islamabad",
  "SZABIST, Larkana",
  "SZABIST, Hyderabad",
  "SZABIST, Gharo (Thatta)",
  "ISRA University, Hyderabad",
  "ISRA University, Islamabad",
  "IQRA University, Karachi (Gulshan Campus)",
  "IQRA University, Islamabad (H‑9)",
  "IQRA University, Malir (Airport Road) Karachi",
  "IQRA University, M‑9 Scheme 33 Karachi",
  "Abasyn University, Peshawar",
  "Abasyn University, Islamabad",
  "Hamdard University, Karachi ",
  "Hamdard University, Islamabad",
  "Institute of Business Administration (IBA), Karachi",
  "Institute of Business Administration (IBA), Sukkur",
  "National College of Business Administration & Economics, Lahore",
  "National College of Business Administration & Economics, Multan",
  "National College of Business Administration & Economics, Bahawalpur",
  "National College of Business Administration & Economics, Rahim Yar Khan",
  "Qurtuba University of Science & Information Technology, Dera Ismail Khan",
  "Qurtuba University of Science & Information Technology, Peshawar",
  "University of Management & Technology, Lahore",
  "University of Management & Technology, Sialkot",
  "The Riphah International University, Rawalpindi",
  "The Riphah International University, Lahore",
  "The Riphah International University, Faisalabad",
  "Al‑Hamd Islamic University, Quetta",
  "Greenwich University, Karachi",
  "Hajvery University, Lahore",
  "Aga Khan University, Karachi",
  "Foundation University, Islamabad",
  "Foundation University, Sialkot",
  "Ilma University, Karachi",
  "Zia‑ud‑Din University, Karachi",
  "Zia‑ud‑Din University, Sukkur",
  "Mohi‑ud‑Din Islamic University, Nerian Sharif",
  "Mohi‑ud‑Din Islamic University, Mirpur AJ&K",
   // Federal Government Colleges (FGEI)
  "Federal Government College, Karachi, Sindh",
  "Federal Government Inter Girls College, Karachi Cantonment, Sindh",
  "Federal Govt Degree College, Lahore Cantt, Punjab",
  "Federal Govt Degree College, Gujranwala Cantt, Punjab",
  "Federal Govt Degree College, Qasim Bela Road, Multan, Punjab",
  "Federal Govt Degree College, Attock Cantt, Punjab",
  "Federal Govt Liaquat Ali Degree College for Boys, Rawalpindi, Punjab",
  "Federal Govt Inter College, Sialkot, Punjab",
  "Federal Govt Inter College, Jhelum, Punjab",
  
  // Government/Board Colleges (Intermediate & Degree)
  "Adamjee Government Science College, Karachi, Sindh",
  "D. J. Sindh Government Science College, Karachi, Sindh",
  "Sindh Muslim Government Arts & Commerce College, Karachi, Sindh",
  "Government Islamia Science College, Karachi, Sindh",  
  "Government Degree College Memon Goth, Karachi, Sindh",
  "Government College for Men, North Nazimabad, Karachi, Sindh",
  "Government College for Women, Shahrah‑e‑Liaquat, Karachi, Sindh",
  "Bamm P.E.C.H.S. Government College for Women, Karachi, Sindh",
  "St. Joseph’s Government College for Women, Karachi, Sindh",
  "Sir Syed Government Girls College, Karachi, Sindh",
  "Khatoon‑e‑Pakistan Government College for Women, Karachi, Sindh",
  
  "Government College Gujranwala, Gujranwala, Punjab",
  "Government Peer Yaqoob Shah Degree College, Phalia, Punjab",
  "Government Post Graduate Islamia College, Faisalabad, Punjab",
  "Government Post Graduate College Nowshera, Nowshera, Khyber Pakhtunkhwa",
  
  // A‑Level / Cambridge & College Prep (Major)
  "Nixor College (A‑Level), Karachi, Sindh",
  "Cedar College (A‑Level), Karachi, Sindh",
  "The Lyceum School (A‑Level), Clifton, Karachi, Sindh",
  "Karachi Grammar School (A‑Level), Karachi, Sindh",
  "Alpha College (A‑Level), DHA, Karachi, Sindh",
  "Roots Millennium College (A‑Level/IB), Karachi, Sindh",
  "Beaconhouse College (A‑Level), Karachi, Sindh",
  "British International School (A‑Level), Karachi, Sindh",
  
  // Other Notable Colleges (Various Boards)
  "Agha Khan Higher Secondary School/College (BIEK), Karachi, Sindh",
  "Pakistan Shipowners’ College, North Nazimabad, Karachi, Sindh",
  "DEA Higher Secondary College, Karachi, Sindh",
  "DHA Degree College for Men, Karachi, Sindh",
  "DHA Degree College for Women, Karachi, Sindh",
  "Tabanis College, Karachi, Sindh",
  "Commecs College, Karachi, Sindh",
  "Adamjee Government College for Boys & Girls (Board affiliates), Karachi, Sindh"
];